#include <stdio.h>
int main (void)
{
	const double GRAVITY =9.8;
	const double EFFICIENCY =0.9;
	const double WATER_DENSITY =1000.0;

	double height, flowrate;
	double massPerSecond;
	double powerWatts, powerMW;

	printf("Enter height of the dam(m):");
	scanf("%lf",&height);

	printf("Enter flow rate of water (m^3/s):");
	scanf("%lf" ,&flowrate);

	massPerSecond = flowrate*WATER_DENSITY;
	powerWatts = EFFICIENCY*massPerSecond*GRAVITY*height;

	powerMW = powerWatts/1000000.0;

	printf("Predicted power generated by the hydroelectric dam: %2f megawatts\n",powerMW);
	return 0;
}
